// <auto-generated />
using System;
using Beatport2Rss.Builder.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beatport2Rss.Builder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BuilderDbContext))]
    partial class BuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("builder")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Artists.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BeatportId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatportUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BeatportId")
                        .IsUnique();

                    b.ToTable("Artists", "builder");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BeatportId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatportUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BeatportId")
                        .IsUnique();

                    b.ToTable("Labels", "builder");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Releases.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BeatportId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatportUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BeatportId")
                        .IsUnique();

                    b.HasIndex("LabelId");

                    b.ToTable("Releases", "builder");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BeatportId")
                        .HasColumnType("integer");

                    b.Property<string>("BeatportUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("interval");

                    b.Property<string>("MixName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SampleUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BeatportId")
                        .IsUnique();

                    b.HasIndex("ReleaseId");

                    b.ToTable("Tracks", "builder");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Releases.Release", b =>
                {
                    b.HasOne("Beatport2Rss.Builder.Domain.Labels.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Beatport2Rss.Builder.Domain.Releases.ReleaseArtist", "Artists", b1 =>
                        {
                            b1.Property<Guid>("ReleaseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("ReleaseId", "ArtistId", "Type");

                            b1.HasIndex("ArtistId");

                            b1.ToTable("ReleaseArtists", "builder");

                            b1.HasOne("Beatport2Rss.Builder.Domain.Artists.Artist", null)
                                .WithMany()
                                .HasForeignKey("ArtistId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ReleaseId");
                        });

                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Tracks.Track", b =>
                {
                    b.HasOne("Beatport2Rss.Builder.Domain.Releases.Release", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Beatport2Rss.Builder.Domain.Tracks.TrackArtist", "Artists", b1 =>
                        {
                            b1.Property<Guid>("TrackId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("TrackId", "ArtistId", "Type");

                            b1.HasIndex("ArtistId");

                            b1.ToTable("TrackArtists", "builder");

                            b1.HasOne("Beatport2Rss.Builder.Domain.Artists.Artist", null)
                                .WithMany()
                                .HasForeignKey("ArtistId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Artists");
                });

            modelBuilder.Entity("Beatport2Rss.Builder.Domain.Releases.Release", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
