// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Beatport2Rss.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class UpdatedSubscriptionIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportId_BeatportType",
                table: "Subscriptions");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportId",
                table: "Subscriptions",
                column: "BeatportId");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId_BeatportSlug",
                table: "Subscriptions",
                columns: new[] { "BeatportType", "BeatportId", "BeatportSlug" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportId",
                table: "Subscriptions");

            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId_BeatportSlug",
                table: "Subscriptions");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportId_BeatportType",
                table: "Subscriptions",
                columns: new[] { "BeatportId", "BeatportType" },
                unique: true);
        }
    }
}
