// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Beatport2Rss.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddedIndexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Tags_UserId_Slug",
                table: "Tags",
                columns: new[] { "UserId", "Slug" });

            migrationBuilder.CreateIndex(
                name: "IX_Feeds_UserId_Slug",
                table: "Feeds",
                columns: new[] { "UserId", "Slug" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Tags_UserId_Slug",
                table: "Tags");

            migrationBuilder.DropIndex(
                name: "IX_Feeds_UserId_Slug",
                table: "Feeds");
        }
    }
}
