// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Beatport2Rss.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddedSubscriptionSlug : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportId",
                table: "Subscriptions");

            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportSlug",
                table: "Subscriptions");

            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId_BeatportSlug",
                table: "Subscriptions");

            migrationBuilder.AddColumn<string>(
                name: "Slug",
                table: "Subscriptions",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false);

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId",
                table: "Subscriptions",
                columns: new[] { "BeatportType", "BeatportId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_Slug",
                table: "Subscriptions",
                column: "Slug",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId",
                table: "Subscriptions");

            migrationBuilder.DropIndex(
                name: "IX_Subscriptions_Slug",
                table: "Subscriptions");

            migrationBuilder.DropColumn(
                name: "Slug",
                table: "Subscriptions");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportId",
                table: "Subscriptions",
                column: "BeatportId");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportSlug",
                table: "Subscriptions",
                column: "BeatportSlug");

            migrationBuilder.CreateIndex(
                name: "IX_Subscriptions_BeatportType_BeatportId_BeatportSlug",
                table: "Subscriptions",
                columns: new[] { "BeatportType", "BeatportId", "BeatportSlug" },
                unique: true);
        }
    }
}
